@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Reports</h1>
        <p>Access all the reports generated by our platform here. You can view, download, and analyze the data.</p>
        <p>Please contact us if you need custom reports or have any queries regarding the data.</p>
    </div>
@endsection
